# goose配置
# [GooseBuild]和[GooseSearch]是框架所需要的配置信息
# 策略自定义的配置

[GooseBuild]
# 建库最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 建库数据库的相关配置
    [GooseBuild.DataBase]
    # 索引库的目标位置
    DbPath = "data/goosedemo"
    # 正排转倒排的内存缓冲区最大容纳term数量.
    # 越大越好,减少读写磁盘数,随之内存占用越多.
    TransformMaxTermCnt = 10000000
    # 索引库最大id数
    MaxId = 5000000
    # 索引文件最大文件大小,单位(B),1G = 1073741824B
    MaxIndexFileSize = 1073741824
    # Data文件最大文件大小,单位(B),1G = 1073741824B
    MaxDataFileSize = 1073741824
    # 每个doc的Value大小,单位(B)
    ValueSize = 32

[GooseSearch]
# 检索最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 检索相关配置
    [GooseSearch.Search]
    # 检索并发协程数
    GoroutineNum = 100
    # 检索服务端口
    ServerPort = 7788
    # 接受请求的网络缓冲区(byte)
    RequestBufferSize = 1024
    # 发送请求的网络缓冲区(byte)
    ResponseBufferSize = 1048576

    # 更新相关配置
    [GooseSearch.Index]
    # 服务端口
    ServerPort = 7789
    # 接受请求的网络缓冲区(byte)
    RequestBufferSize = 10240

    # 定时刷新相关配置
    [GooseSearch.Refresh]
    # 每隔多少秒刷新一次
    SleepTime = 10


[Strategy]
    # 建库策略
    [Strategy.Indexer]
        [Strategy.Indexer.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"
    # 检索策略
    [Strategy.Searcher]
        [Strategy.Searcher.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

